
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test11?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

#    redis:
#      jedis:
#        pool:
#          maxWaitMillis: 1000
#          maxIdle: 100
#          host: 127.0.0.1
#          port: 6379
#          password: 123456
#          timeout: 7200
#          max-active: 3000
#          max-wait: 5000
#          min-idle: 1weqaHGFD
mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml
  type-aliases-package: com.springtest.model
